"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Introduction.ipynb.

# %% auto #0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_Introduction.ipynb #fb303033
def say_hello(to):
    "Say Hello to someone."
    return f"Hello {to}!"

# %% ../nbs/00_Introduction.ipynb #479cceeb
def foo(): pass
