"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb #64d61d4f
def say_hello(to):
    "Say Hello to someone."
    return f"Hello {to}!"

# %% ../nbs/00_core.ipynb #0dc22519
def foo(): pass
