# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Introduction.ipynb.

# %% auto #0
__all__ = ['say_hello']

# %% ../nbs/00_Introduction.ipynb #299b2bc8
def say_hello(to):
    "Say Hello to someone."
    return f"Hello {to}!"
